In [ ]:
Python library :-
                   NUMPY is also part of python library and its mean (Numerical Python) 
                   its also work like manipulation and mathematical operation in python
use numpy 
!pip install numpy

In [2]:
import numpy as np      #this is access numpy in your file

""" Array => array also collection of data and its work like list and you access array in python throw by numpy library and 
          array size fix ones you create here after we not change thier size """
n = np.array([12,3,5,7,89,5])       # array in numpy
print(n)
print(type(n))      #type of variable  <class 'numpy.ndarray'>

#1. NDIM => this is for number of dimensions of array
n.ndim

# .2 Shape
m = np.array(([23,34,3],[34,5,43]))
m.shape             #its also give array size how many rows and columns in your array

# .3 Size
n.size           #its give how many elements in your array its give number of elements


[12  3  5  7 89  5]
<class 'numpy.ndarray'>


6

In [10]:
# Data type (dype )=> its for data type of your data in present in array
m = np.array(([34,54,35.3],[44,5,4]))
print(m.dtype)


float64


In [ ]:
Arange in numpy =>
                   arange its work like range but in numpy its work with name arange
Linspace in numpy =>
                     linspace its also work like arange and in linspace are also give dype attribute

In [6]:
# arange use in python
c = np.arange(1,20)
c

""" Arange with reshape in numpy """
d = np.arange(0,12).reshape(4,3)
d            #its arrange your value in array 
a = np.arange(0,20).reshape(4,5)
a

#linspace
a = np.linspace(-10,20,dtype=int)
a
v = np.linspace(-5,2,2,dtype = float)
v

array([-5.,  2.])

In [19]:
""" ZEROS = > np.zeros in numpy its create array use with zero in elements """
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
""" ONES = > np.ones in numpy its create array use with one in elements  """
n = np.ones((4,6))
n

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
Random =>
         random its also work in numpy and its use to create random number in array and in python
Rand  =>
         rand its also work in numpy and its use to create random number in array and in python and its also take single ()
Randint =>
           randint its also work in numpy and its use to create int random number in array and in python its only create int number
Seed =>
       seed its use to control random frequency

In [28]:
b = np.random.random((5,3))
b

# rand
v = np.random.rand(2,3)
v

# randint
m = np.random.randint(1,20,5)
m

array([ 3,  4, 15, 18,  8], dtype=int32)

In [13]:
""" Splitting =>
              splitting in python  its split elements in array
 """
n = np.arange(0,12).reshape(4,3)
m = np.split(n,4)
m


[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [17]:
""" TRANSPOSE => 
             transpose its use to change row number in column and column number in row number """
n = np.arange(0,12).reshape(3,4)
v = np.transpose(n)
v

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [21]:
""" RAVEL =>
            Ravel its use to convert into flat array """
b = np.arange(0,6).reshape(3,2)
np.ravel(b)

array([0, 1, 2, 3, 4, 5])